FROM python:3-slim

RUN apt-get update && apt-get install -y wget

RUN pip install --no-cache-dir pandas sqlalchemy psycopg2-binary

WORKDIR /app
COPY upload-data.py upload-data.py

ENTRYPOINT ["python", "upload-data.py"]