
services: 
  postgres: 
    image: postgres:13
    container_name: postgres_nyc_taxi
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root 
      POSTGRES_DB: nyc_taxi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin: 
    image: dpage/pgadmin4
    container_name: pgadmin_nyc_taxi
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root 
    ports: 
    - 8080:80
    depends_on:
      - postgres
volumes:
  pgdata: